spring.application.name=Hotel-ERP

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Hotel-ERP
spring.datasource.username=postgres
spring.datasource.password=log3in7dat

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT Secret key
jwt.secret=2f8e2837a191f560408df9d57832b0480fa0b3faa2c4fe0b9a015bd8af41e807
